docker-build:
  docker build -t robot_ros2_publisher .

docker-run-simulated:
  docker run --rm --network host robot_ros2_publisher

docker-run-with-arduino:
  docker run --rm --device /dev/ttyACM1 --network host robot_ros2_publisher

dev: docker-build docker-run-simulated
